version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  docs:
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: always
