apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repo-demo-secret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GVengelen/ready-changeset-argo.git
    targetRevision: HEAD
    path: argocd/apps
    directory:
      recurse: true
      include: argocd-repo-demo-secret.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
