apiVersion: v1
kind: Secret
metadata:
  name: repo-demo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
stringData:
  url: ghcr.io/gvengelen/helm
  enableOCI: "true"
  name: demo
  project: default
  type: helm
