apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/GVengelen/ready-changeset-argo.git'
    targetRevision: HEAD
    path: charts/next-app
    helm:
      values: |
        fullnameOverride: web
        image:
          repository: ghcr.io/gvengelen/ready-changeset-argo-web
          tag: a4ea1a3
        service:
          port: 3000
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
