apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docs
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "docs=ghcr.io/gvengelen/ready-changeset-argo-docs"
    argocd-image-updater.argoproj.io/docs.helm.image-tag:: image.tag
    argocd-image-updater.argoproj.io/docs.helm.image-name: image.name
    argocd-image-updater.argoproj.io/docs.update-strategy: "newest-build"
    argocd-image-updater.argoproj.io/write-back-method: "git:secret:argocd/ghcr-repo-creds"
    argocd-image-updater.argoproj.io/git-repository: https://github.com/GVengelen/ready-changeset-argo.git
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:/argocd/values/argocd-app-docs.yaml"
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  sources:
    - repoURL: https://github.com/GVengelen/ready-changeset-argo.git
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://github.com/GVengelen/ready-changeset-argo.git'
      targetRevision: HEAD
      path: charts/next-app
      helm:
        valueFiles:
          - $values/argocd/values/argocd-app-docs.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: docs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
