apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 0.11.0
      chart: argocd-image-updater
      helm:
        values: |
          config:
            gitCommitTemplate: |
              build: automatic update of "{{`{{ .AppName }}`}}"

              "{{`{{ range .AppChanges -}}`}}"
              updates image "{{`{{ .Image }}`}}" tag "{{`{{ .OldTag }}`}}" to "{{`{{ .NewTag }}`}}"
              "{{`{{ end -}}`}}"        
            registries:
            - name: GHCR
              api_url: https://ghcr.io/GVengelen/
              prefix: ghcr.io/GVengelen
              default: true
            applicationsAPIKind: kubernetes
            logLevel: info
            gitCommitUser: "argocd-bot"
            gitCommitMail: "argocd-bot@example.com"
            gitCommitSigningKey: ""
            gitCommitSignOff: "false"
            gitCommitSigningMethod: "none"
            disableKubeEvents: "false"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
