name: Helm Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Release Helm chart using release-please
        uses: googleapis/release-please-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.DCS_PAT }}
        with:
          skip-github-release: false
          token: ${{ steps.get_workflow_token.outputs.token }}
          config-file: charts/release-please-config.json
          manifest-file: charts/.release-please-manifest.json