name: Helm Release
on:
  workflow_call:
    inputs:
      path:
        description: 'Helm Chart path'
        required: true
        type: string
      environment:
        type: string
        required: true
      helm_version:
        description: A valid SemVer 2 version string. This will be the version of the helm chart image on the repository
        type: string
        required: true
      name:
        type: string
        required: true
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "${{github.head_ref || github.ref }}"

      - uses: azure/setup-helm@v4.2.0

      - name: Get GitHub App Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Log in to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.get_workflow_token.outputs.token }}

      - name: Package and Push Helm Chart to ghcr.io
        run: |
          cd ${{ inputs.path }}
          helm package . --version ${{ inputs.helm_version }} --dependency-update
          owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          helm push ./*.tgz oci://ghcr.io/$owner/helm
