name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9.0.0
          
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          setupGitUser: true
          createGithubReleases: true
          commitMode: github-api
        env:
          PNPM_HOME: /runner/setup-pnpm/node_modules/.bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Tag Release
        if: steps.changesets.outputs.hasChangesets == 'false' && contains(github.event.head_commit.message, 'Version Packages')
        run: |
          pnpm run changeset:tag
          git push origin main --follow-tags
